/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package KlinikPekapuran;
import java.sql.*;
import javax.swing.table.*;
/**
 *
 * @author Nur
 */
public class coba extends javax.swing.JInternalFrame {
    public final Connection Conn = new Koneksi().Connect();
    private DefaultTableModel tablemode;
    
    public void penomoran(){
        int baris = tablemode.getRowCount();
        for (int a=0; a<baris; a++){
            String nomor = String.valueOf(a+1);
            tablemode.setValueAt (nomor+".",a, 0);
        }
        
    }
    
    public void isiTabel(){
        Object[] baris ={"No","Id-Dok", "Nama Dokter","Spesialis","Jadwal"};
        tablemode = new DefaultTableModel(null, baris);
        jTable1.setModel(tablemode);
        String sql ="select * from dokter order by id_dokter";
        try{
            java.sql.Statement stt = Conn.createStatement();
            ResultSet hasil =stt.executeQuery(sql);
            while (hasil.next()){
                String id_dokter = hasil.getString("id_dokter");
                String nama_dokter = hasil.getString("nama_dokter");
                String spesialisasi_dokter = hasil.getString("spesialisasi_dokter");
                String jadwal_dokter = hasil.getString("jadwal_dokter");
                
                String[] data = {"",id_dokter, nama_dokter, spesialisasi_dokter, jadwal_dokter};
                tablemode.addRow(data);
                penomoran();
            }
        } catch (SQLException e){
            }
    }
    /** Creates new form coba */
    public coba() {
        initComponents();
        isiTabel();
        penomoran();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
