/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KlinikPekapuran;
import java.sql.*;

/**
 *
 * @author Nur
 */
public class MenuUtama_Cancel extends javax.swing.JFrame {
    private final Connection Conn = new Koneksi().Connect();
    private Dokter Dokter;
    private User User;
    private Fasilitas Fasilitas;
    private Kamar Kamar;
    
    private PendaftaranPasien Pendaftaran;
    private Diagnosa Diagnosa;
    private Resep Resep;
    private Biaya Biaya;
    
    private coba coba;
    
    private void initForm(){
        Dokter = new Dokter();
        User = new User();
        Fasilitas = new Fasilitas();
        Kamar = new Kamar();
             
        Pendaftaran = new PendaftaranPasien();
        Diagnosa = new Diagnosa();
        
        coba=new coba();
        
    }

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama_Cancel() {
        initComponents();
        initForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        DataInduk = new javax.swing.JMenu();
        menuUser = new javax.swing.JMenuItem();
        menuDokter = new javax.swing.JMenuItem();
        menuFasilitas = new javax.swing.JMenuItem();
        menuKamar = new javax.swing.JMenuItem();
        Pelayanan = new javax.swing.JMenu();
        menuPendaftaran = new javax.swing.JMenuItem();
        menuDiagnosa = new javax.swing.JMenuItem();
        menuResep = new javax.swing.JMenuItem();
        menuBiaya = new javax.swing.JMenuItem();
        Laporan = new javax.swing.JMenu();
        menuUser5 = new javax.swing.JMenuItem();
        menuUser6 = new javax.swing.JMenuItem();
        menuUser7 = new javax.swing.JMenuItem();
        MenuClose = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");
        setBackground(new java.awt.Color(0, 153, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);
        setIconImages(null);

        jDesktopPane1.setBackground(new java.awt.Color(51, 255, 51));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jDesktopPane1.setForeground(new java.awt.Color(0, 204, 0));
        jDesktopPane1.setToolTipText("KLINIK PEKAPURAN");
        jDesktopPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopPane1.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(204, 255, 102));

        DataInduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/DataInduk.png"))); // NOI18N
        DataInduk.setText("Data Induk");
        DataInduk.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DataInduk.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        DataInduk.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DataInduk.setIconTextGap(8);
        DataInduk.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        DataInduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataIndukActionPerformed(evt);
            }
        });

        menuUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu.png"))); // NOI18N
        menuUser.setText("User");
        menuUser.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        menuUser.setIconTextGap(1);
        menuUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUserActionPerformed(evt);
            }
        });
        DataInduk.add(menuUser);

        menuDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu.png"))); // NOI18N
        menuDokter.setText("Dokter");
        menuDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDokterActionPerformed(evt);
            }
        });
        DataInduk.add(menuDokter);

        menuFasilitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu.png"))); // NOI18N
        menuFasilitas.setText("Fasilitas");
        menuFasilitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFasilitasActionPerformed(evt);
            }
        });
        DataInduk.add(menuFasilitas);

        menuKamar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu.png"))); // NOI18N
        menuKamar.setText("Kamar");
        menuKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKamarActionPerformed(evt);
            }
        });
        DataInduk.add(menuKamar);

        jMenuBar1.add(DataInduk);

        Pelayanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/layanan.png"))); // NOI18N
        Pelayanan.setText("Pelayanan");
        Pelayanan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Pelayanan.setIconTextGap(8);
        Pelayanan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        menuPendaftaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu.png"))); // NOI18N
        menuPendaftaran.setText("Pendaftaran");
        menuPendaftaran.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        menuPendaftaran.setIconTextGap(1);
        menuPendaftaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPendaftaranActionPerformed(evt);
            }
        });
        Pelayanan.add(menuPendaftaran);

        menuDiagnosa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu.png"))); // NOI18N
        menuDiagnosa.setText("Diagnosa Dokter");
        menuDiagnosa.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        menuDiagnosa.setIconTextGap(1);
        menuDiagnosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDiagnosaActionPerformed(evt);
            }
        });
        Pelayanan.add(menuDiagnosa);

        menuResep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu.png"))); // NOI18N
        menuResep.setText("Resep Obat");
        menuResep.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        menuResep.setIconTextGap(1);
        menuResep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuResepActionPerformed(evt);
            }
        });
        Pelayanan.add(menuResep);

        menuBiaya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu.png"))); // NOI18N
        menuBiaya.setText("Informasi Biaya");
        menuBiaya.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        menuBiaya.setIconTextGap(1);
        menuBiaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBiayaActionPerformed(evt);
            }
        });
        Pelayanan.add(menuBiaya);

        jMenuBar1.add(Pelayanan);

        Laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/laporan.png"))); // NOI18N
        Laporan.setText("Laporan");
        Laporan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Laporan.setIconTextGap(8);
        Laporan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        menuUser5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu.png"))); // NOI18N
        menuUser5.setText("Cetak Kartu Pasien");
        menuUser5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        menuUser5.setIconTextGap(1);
        menuUser5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUser5ActionPerformed(evt);
            }
        });
        Laporan.add(menuUser5);

        menuUser6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu.png"))); // NOI18N
        menuUser6.setText("Data Kunjungan");
        menuUser6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        menuUser6.setIconTextGap(1);
        menuUser6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUser6ActionPerformed(evt);
            }
        });
        Laporan.add(menuUser6);

        menuUser7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu.png"))); // NOI18N
        menuUser7.setText("Data Pasien");
        menuUser7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        menuUser7.setIconTextGap(1);
        menuUser7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUser7ActionPerformed(evt);
            }
        });
        Laporan.add(menuUser7);

        jMenuBar1.add(Laporan);

        MenuClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close.png"))); // NOI18N
        MenuClose.setText("Close");
        MenuClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MenuClose.setIconTextGap(8);
        MenuClose.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MenuClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCloseActionPerformed(evt);
            }
        });
        jMenuBar1.add(MenuClose);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDokterActionPerformed
    if(!Dokter.isVisible()){
        jDesktopPane1.add(Dokter);
        Dokter.show();
        
        User.dispose();
        Fasilitas.dispose();
        Kamar.dispose();
        Pendaftaran.dispose();
        Diagnosa.dispose();
        Resep.dispose();
        Biaya.dispose();            
        }
    }//GEN-LAST:event_menuDokterActionPerformed

    private void MenuCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCloseActionPerformed
    dispose();
    }//GEN-LAST:event_MenuCloseActionPerformed

    private void menuUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUserActionPerformed
    if(!User.isVisible()){
        jDesktopPane1.add(User);
        User.show();
        
        Dokter.dispose();
        Fasilitas.dispose();
        Kamar.dispose();
        Pendaftaran.dispose();
        Diagnosa.dispose();
        Resep.dispose();
        Biaya.dispose();            

        }
    }//GEN-LAST:event_menuUserActionPerformed

    private void menuFasilitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFasilitasActionPerformed
        if(!Fasilitas.isVisible()){
            jDesktopPane1.add(Fasilitas);
            Fasilitas.show();
            
            User.dispose();
            Dokter.dispose();
            Kamar.dispose();
            Pendaftaran.dispose();
            Diagnosa.dispose();
            Resep.dispose();
            Biaya.dispose();
        }
    }//GEN-LAST:event_menuFasilitasActionPerformed

    private void menuKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKamarActionPerformed
        if(!Kamar.isVisible()){
            jDesktopPane1.add(Kamar);
            Kamar.show();
            
            User.dispose();
            Dokter.dispose();
            Fasilitas.dispose();
            Pendaftaran.dispose();
            Diagnosa.dispose();
            Resep.dispose();
            Biaya.dispose();
        }
    }//GEN-LAST:event_menuKamarActionPerformed

    private void menuPendaftaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPendaftaranActionPerformed
    if(!Pendaftaran.isVisible()){
            jDesktopPane1.add(Pendaftaran);
            Pendaftaran.show();
            
            User.dispose();
            Dokter.dispose();
            Kamar.dispose();
            Fasilitas.dispose();
            Diagnosa.dispose();
            Resep.dispose();
            Biaya.dispose();
        }
    }//GEN-LAST:event_menuPendaftaranActionPerformed

    private void menuDiagnosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDiagnosaActionPerformed
        if(!Diagnosa.isVisible()){
            jDesktopPane1.add(Diagnosa);
            Diagnosa.show();
            
            User.dispose();
            Dokter.dispose();
            Kamar.dispose();
            Pendaftaran.dispose();
            Fasilitas.dispose();
            Resep.dispose();
            Biaya.dispose();
        }
    }//GEN-LAST:event_menuDiagnosaActionPerformed

    private void menuResepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuResepActionPerformed
        if(!Resep.isVisible()){
            jDesktopPane1.add(Resep);
            Resep.show();
            
            User.dispose();
            Dokter.dispose();
            Kamar.dispose();
            Pendaftaran.dispose();
            Diagnosa.dispose();
            Fasilitas.dispose();
            Biaya.dispose();
        }
    }//GEN-LAST:event_menuResepActionPerformed

    private void menuBiayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBiayaActionPerformed
        if(!Biaya.isVisible()){
            jDesktopPane1.add(Biaya);
            Biaya.show();
            
            User.dispose();
            Dokter.dispose();
            Kamar.dispose();
            Pendaftaran.dispose();
            Diagnosa.dispose();
            Resep.dispose();
            Fasilitas.dispose();
        }
    }//GEN-LAST:event_menuBiayaActionPerformed

    private void menuUser5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUser5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuUser5ActionPerformed

    private void menuUser6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUser6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuUser6ActionPerformed

    private void menuUser7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUser7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuUser7ActionPerformed

    private void DataIndukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataIndukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataIndukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama_Cancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama_Cancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama_Cancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama_Cancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama_Cancel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu DataInduk;
    private javax.swing.JMenu Laporan;
    private javax.swing.JMenu MenuClose;
    private javax.swing.JMenu Pelayanan;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuBiaya;
    private javax.swing.JMenuItem menuDiagnosa;
    private javax.swing.JMenuItem menuDokter;
    private javax.swing.JMenuItem menuFasilitas;
    private javax.swing.JMenuItem menuKamar;
    private javax.swing.JMenuItem menuPendaftaran;
    private javax.swing.JMenuItem menuResep;
    private javax.swing.JMenuItem menuUser;
    private javax.swing.JMenuItem menuUser5;
    private javax.swing.JMenuItem menuUser6;
    private javax.swing.JMenuItem menuUser7;
    // End of variables declaration//GEN-END:variables
}
