/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KlinikPekapuran;

import java.sql.*;
import java.text.*;
import java.time.Instant;
import java.util.Date;
import java.util.logging.*;
import javax.swing.table.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Nur
 */
public class PoliUmum extends javax.swing.JInternalFrame {
    public final Connection Conn = new Koneksi().Connect();
    private DefaultTableModel tablemode;
    
    public void ukuranKolom(){
        TableColumn kolom;
        tabelPasienUmum.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
    }
    
    public void tabelPasienUmum(){
        Object baris[]={"Tgl. Berobat", "ID Pasien", "Nama Pasien", "Jenis Kelamin", "Keluhan", "Dokter", "Resep", "Diagnosa"};
        tablemode = new DefaultTableModel(null, baris);
        tabelPasienUmum.setModel(tablemode);
        String sql = " select * from poliumum order by tgl_berobat desc";
        try{
            java.sql.Statement put = Conn.createStatement();
            ResultSet hasil = put.executeQuery(sql);
            while (hasil.next()){
                String tgl_berobat = hasil.getString("tgl_berobat");
                String id_pasien = hasil.getString("id_pasien");
                String nama_pasien = hasil.getString("nama_pasien");
                String jenis_kelamin = hasil.getString("jenis_kelamin");
                String keluhan = hasil.getString("keluhan");
                String dokter = hasil.getString("dokter");
                String resep = hasil.getString("resep");
                String diagnosa = hasil.getString("diagnosa");
                
                String hasilAll[] = {tgl_berobat, id_pasien, nama_pasien, jenis_kelamin, keluhan, dokter, resep, diagnosa};
                tablemode.addRow(hasilAll);
                ukuranKolom();
            }
            
        } catch (Exception e){} 
    }
    
    
    
    
    /**
     * Creates new form Pendaftaran
     */
    public PoliUmum() {
        initComponents();
        tabelPasienUmum();
        ukuranKolom();
        
    }
    
    protected void blank(){
        id_pasien.setText("");
        nama_pasien.setText("");
        jenis_kelamin.setSelectedIndex(0);
        tgl_berobat.setDate(Date.from(Instant.now()));
        keluhan.setText("");
        dokter_PoliUmum.setSelectedIndex(0);
        resep_obat.setText("");
        diagnosa.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        id_pasien = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nama_pasien = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jenis_kelamin = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tgl_berobat = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        keluhan = new javax.swing.JTextArea();
        HapusPoliUmum = new javax.swing.JButton();
        SimpanPoliUmum = new javax.swing.JButton();
        UbahPoliUmum = new javax.swing.JButton();
        CariPasien = new javax.swing.JButton();
        dokter_PoliUmum = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resep_obat = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        diagnosa = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        pencarian = new javax.swing.JTextField();
        Cari = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelPasienUmum = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1541, 800));

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pelayanan - Poli Umum");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("No. Pasien");

        id_pasien.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nama Pasien");

        nama_pasien.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Jenis Kelamin");

        jenis_kelamin.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jenis_kelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Laki-laki", "Perempuan" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tanggal Berobat");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Keluhan");

        keluhan.setColumns(20);
        keluhan.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        keluhan.setRows(5);
        jScrollPane1.setViewportView(keluhan);

        HapusPoliUmum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        HapusPoliUmum.setText("Hapus");
        HapusPoliUmum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusPoliUmumActionPerformed(evt);
            }
        });

        SimpanPoliUmum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SimpanPoliUmum.setText("Simpan");
        SimpanPoliUmum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanPoliUmumActionPerformed(evt);
            }
        });

        UbahPoliUmum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UbahPoliUmum.setText("Ubah");
        UbahPoliUmum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbahPoliUmumActionPerformed(evt);
            }
        });

        CariPasien.setBackground(new java.awt.Color(0, 102, 102));
        CariPasien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CariPasien.setText("Cari");
        CariPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariPasienActionPerformed(evt);
            }
        });

        dokter_PoliUmum.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        dokter_PoliUmum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Abu Bakar", "Ibnu Sina", "Yopie", "Ibnu Malik" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Dokter");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Resep Obat");

        resep_obat.setColumns(20);
        resep_obat.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        resep_obat.setRows(5);
        jScrollPane2.setViewportView(resep_obat);

        diagnosa.setColumns(20);
        diagnosa.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        diagnosa.setRows(5);
        jScrollPane4.setViewportView(diagnosa);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Diagnosa");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(CariPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tgl_berobat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nama_pasien)
                            .addComponent(jenis_kelamin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(id_pasien)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(dokter_PoliUmum, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(UbahPoliUmum, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                .addComponent(HapusPoliUmum)
                                .addGap(60, 60, 60)
                                .addComponent(SimpanPoliUmum))
                            .addComponent(jScrollPane4))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(id_pasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CariPasien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(nama_pasien, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jenis_kelamin, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(tgl_berobat, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(dokter_PoliUmum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SimpanPoliUmum)
                    .addComponent(HapusPoliUmum)
                    .addComponent(UbahPoliUmum, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(141, 141, 141))
        );

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Database Pasien Poli Umum");

        pencarian.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N

        Cari.setBackground(new java.awt.Color(255, 255, 255));
        Cari.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cari.setForeground(new java.awt.Color(255, 255, 255));
        Cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Search.png"))); // NOI18N
        Cari.setBorderPainted(false);
        Cari.setContentAreaFilled(false);
        Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariActionPerformed(evt);
            }
        });

        tabelPasienUmum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        tabelPasienUmum.setRowHeight(30);
        tabelPasienUmum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPasienUmumMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tabelPasienUmum);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cari, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(115, 115, 115))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Cari, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pencarian))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CariPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariPasienActionPerformed
        // TODO add your handling code here:
        try{
            String sql= "SELECT * FROM pasien WHERE id_pasien LIKE '%" + id_pasien.getText() + "%'" ;
                        java.sql.Statement put = Conn.createStatement();
                        ResultSet rs = put.executeQuery(sql);
            
                        if(rs.next()){
                         
                        String add1 = rs.getString("nama_pasien");
                        nama_pasien.setText(add1);
                        String add2 = rs.getString("jenis_kelamin");
                        jenis_kelamin.setSelectedItem(add2);
                        }
        }catch(Exception e){}
    }//GEN-LAST:event_CariPasienActionPerformed

    private void SimpanPoliUmumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanPoliUmumActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        String tgl = String.valueOf(format.format(tgl_berobat.getDate())); 
        
        String sql = "insert into poliumum values (?,?,?,?,?,?,?,?)";
            try{
                PreparedStatement stat = Conn.prepareStatement(sql);
                stat.setString(1, id_pasien.getText());
                stat.setString(2, nama_pasien.getText());
                stat.setString(3, jenis_kelamin.getSelectedItem().toString());
                stat.setString(4, tgl);
                stat.setString(5, keluhan.getText());
                stat.setString(6, dokter_PoliUmum.getSelectedItem().toString());
                stat.setString(7, resep_obat.getText());
                stat.setString(8, diagnosa.getText());

                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Lanjut Untuk Simpan");
                blank();
                id_pasien.requestFocus();
                tabelPasienUmum();
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Data gagal disimpan"+e);
                tabelPasienUmum();
                
            }
    }//GEN-LAST:event_SimpanPoliUmumActionPerformed

    private void HapusPoliUmumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusPoliUmumActionPerformed
        // TODO add your handling code here:
        tabelPasienUmum();
        blank();
    }//GEN-LAST:event_HapusPoliUmumActionPerformed

    private void UbahPoliUmumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahPoliUmumActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat tglKlik = new SimpleDateFormat("yyyy-MM-dd");
        String tgl = String.valueOf(tglKlik.format(tgl_berobat.getDate()));
        try{
            String sql = "update poliumum set "
                    + "id_pasien=?, "
                    + "nama_pasien=?,"
                    + "jenis_kelamin=?,"
                    + "tgl_berobat=?,"
                    + "keluhan=?,"
                    + "dokter=?,"
                    + "resep=?,"
                    + "diagnosa=? "
                    + "where id_pasien='"+id_pasien.getText()+"'";
            PreparedStatement stat = Conn.prepareStatement(sql);
            stat.setString(1, id_pasien.getText());
            stat.setString(2, nama_pasien.getText());
            stat.setString(3, jenis_kelamin.getSelectedItem().toString());
            stat.setString(4, tgl);
            stat.setString(5, keluhan.getText());
            stat.setString(6, dokter_PoliUmum.getSelectedItem().toString());
            stat.setString(7, resep_obat.getText());
            stat.setString(7, diagnosa.getText());
                
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Lanjut Untuk Ubah Data");
            blank();
            id_pasien.requestFocus();
        }      
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data gagal diubah"+e);
        }
        tabelPasienUmum();
    }//GEN-LAST:event_UbahPoliUmumActionPerformed

    private void CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariActionPerformed
        // TODO add your handling code here:
        try{
            String sql= "SELECT * FROM poliumum WHERE id_pasien like '%" + pencarian.getText() + "%'" +"or nama_pasien like '%" + pencarian.getText()+"%'";
                        java.sql.Statement put = Conn.createStatement();
                        ResultSet rs = put.executeQuery(sql);
            
                        if(rs.next()){
                         
                        String add1 = rs.getString("id_pasien");
                        id_pasien.setText(add1);
                        String add2 = rs.getString("nama_pasien");
                        nama_pasien.setText(add2);
                        String add3 = rs.getString("jenis_kelamin");
                        jenis_kelamin.setSelectedItem(add3);
                        String add4 = rs.getString("tgl_berobat");
                        //tgl_berobat.setDate();Text(add4);
                        //String add4 = rs.getString("keluhan");
                        keluhan.setText(add4);
                        String add5 = rs.getString("dokter");
                        dokter_PoliUmum.setSelectedItem(add5);
                        String add6 = rs.getString("resep");
                        resep_obat.setText(add6);
                        String add7 = rs.getString("diagnosa");
                        diagnosa.setText(add7);
                        Date t = rs.getDate("tgl_berobat");
                        tgl_berobat.setDate(t);
                        }
        }catch(Exception e){}
    
    }//GEN-LAST:event_CariActionPerformed

    private void tabelPasienUmumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPasienUmumMouseClicked
        // TODO add your handling code here:
        SimpleDateFormat tglview = new SimpleDateFormat("yyyy-MM-dd");
        Date dateView = null;

        int baris = tabelPasienUmum.getSelectedRow();

        try {
            
            id_pasien.setText(tabelPasienUmum.getModel().getValueAt(baris, 1).toString());
            nama_pasien.setText(tabelPasienUmum.getModel().getValueAt(baris, 2).toString()); 
            jenis_kelamin.setSelectedItem(tabelPasienUmum.getModel().getValueAt(baris, 3).toString());
            tgl_berobat.setDateFormatString(tabelPasienUmum.getModel().getValueAt(baris, 0).toString());
            keluhan.setText(tabelPasienUmum.getModel().getValueAt(baris, 4).toString());
            dokter_PoliUmum.setSelectedItem(tabelPasienUmum.getModel().getValueAt(baris, 5).toString());
            resep_obat.setText(tabelPasienUmum.getModel().getValueAt(baris, 6).toString());
            diagnosa.setText(tabelPasienUmum.getModel().getValueAt(baris, 7).toString());
                    
        }catch (Exception e) {}
        
        
    }//GEN-LAST:event_tabelPasienUmumMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cari;
    private javax.swing.JButton CariPasien;
    private javax.swing.JButton HapusPoliUmum;
    private javax.swing.JButton SimpanPoliUmum;
    private javax.swing.JButton UbahPoliUmum;
    private javax.swing.JTextArea diagnosa;
    private javax.swing.JComboBox<String> dokter_PoliUmum;
    private javax.swing.JTextField id_pasien;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JComboBox<String> jenis_kelamin;
    private javax.swing.JTextArea keluhan;
    private javax.swing.JTextField nama_pasien;
    private javax.swing.JTextField pencarian;
    private javax.swing.JTextArea resep_obat;
    private javax.swing.JTable tabelPasienUmum;
    private com.toedter.calendar.JDateChooser tgl_berobat;
    // End of variables declaration//GEN-END:variables
}
